services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./symfony:/var/www/symfony
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    ports:
      - "666:80"
    volumes:
      - ./symfony:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  db-data:
